" Author: Ibrahim Rabbani
" Description: My VIM configuration python development
" Url: https://github.com/israbbani/shell_config
"
" Turn of compatibility with Vi just in case
set nocompatible
filetype off

" Add line numbers
set number

" Fix Backspace
set backspace=indent,eol,start

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'gmarik/Vundle.vim'
Plugin 'scrooloose/nerdtree'
Plugin 'jistr/vim-nerdtree-tabs'
Plugin 'tmhedberg/SimpylFold'
Plugin 'vim-scripts/indentpython.vim'
Plugin 'vim-syntastic/syntastic'
Plugin 'nvie/vim-flake8'
Plugin 'kien/ctrlp.vim'
Plugin 'tpope/vim-fugitive'
Bundle 'Valloric/YouCompleteMe'
call vundle#end()
filetype plugin indent on

" Splits to the bottom and right by default
set splitbelow
set splitright

" Enable folding
set foldmethod=indent
set foldlevel=99

" Enable folding with the spacebar
nnoremap <space> za

" Python Indentation
au BufNewFile,BufRead *.py
    \ set tabstop=4 |
    \ set softtabstop=4 |
    \ set shiftwidth=4 |
    \ set textwidth=79 |
    \ set expandtab |
    \ set autoindent |
    \ set fileformat=unix |

highlight BadWhitespace ctermbg=red guibg=darkred
au BufRead,BufNewFile *.py,*.pyw,*.c,*.h match BadWhitespace /\s\+$/

set encoding=utf-8

" YCM 
let g:ycm_autoclose_preview_window_after_completion=1
map <leader>g  :YcmCompleter GoToDefinitionElseDeclaration<CR>

let python_highlight_all=1

" ------------------------------ 
" FZF (Fuzzy Search) Config
" ------------------------------
nmap <C-p> :Files<CR>
" ------------------------------ 
"  End FZF Config
" ------------------------------

" ------------------------------ 
" NERDTree configuration for VIM
" ------------------------------
" Map NERDTree toggle onto a keyboard shortcut
nmap <C-n> :NERDTreeToggle<CR>
nmap <C-m> :NERDTreeTabsFind<CR>
let NERDTreeIgnore=['\.pyc$', '\~$'] "ignore files in NERDTree
" ------------------------------ 
" End NERDTree configuration
" ------------------------------

syntax on
set background=dark
" colorscheme solarized

" Set airline powerline fonts and theme
let g:airline_powerline_fonts = 1
let g:airline_theme='simple'
set laststatus=2

"------------------------------
" THis is for my own good
"------------------------------
" No arrow keys allowed
map <Up> <NOP>
map <Down> <NOP>
map <Left> <NOP>
map <Right> <NOP>
" Mapping CTRL M N to move everything at the cursor to a new line 
map <C-\> i<CR>

"python with virtualenv support
py << EOF
import os
import sys
if 'VIRTUAL_ENV' in os.environ:
  project_base_dir = os.environ['VIRTUAL_ENV']
  activate_this = os.path.join(project_base_dir, 'bin/activate_this.py')
  execfile(activate_this, dict(__file__=activate_this))
EOF
